IF OBJECT_ID('dbo.DATEFROMPARTS', N'FN') IS NOT NULL
	DROP FUNCTION dbo.DATEFROMPARTS
GO

CREATE FUNCTION DATEFROMPARTS (
  @day AS INT
  ,@month AS INT
  ,@year AS INT
)
RETURNS DATETIME

BEGIN
	RETURN DATEADD(day, @day - 1, DATEADD(month, @month - 1, DATEADD(year, @year - 1900, 0)))
END
GO

SELECT dbo.DATEFROMPARTS(1,3,2014) AS 'DATEFROMPARTS'
GO
