IF OBJECT_ID('dbo.REMOVE_NUMBERS', N'FN') IS NOT NULL
	DROP FUNCTION dbo.REMOVE_NUMBERS
GO

CREATE FUNCTION REMOVE_NUMBERS (
	@Input_str AS VARCHAR(MAX)
	)
RETURNS VARCHAR(MAX)

BEGIN
   
  SELECT @Input_str = REPLACE(@Input_str,NUMBER,'')
    FROM [Master].dbo.spt_values
   WHERE TYPE ='P'
     AND NUMBER between 0 and 9
  
  RETURN @Input_str
  
END
GO

SELECT dbo.REMOVE_NUMBERS('A1B2C3D4') AS REMOVE_NUMBERS
GO
